version: '3'

services:
    app:
        image: tolgee/tolgee
        volumes:
            - ./data:/data
            - ./config.yaml:/config.yaml
        ports:
            - '25432:25432' # This is for the database, if using it externally
            - '8080:8080' # Make sure this exposes the app
        env_file:
            - .env
